# KrakatoaRendererPropertyPlugin
# Initial code generated by Softimage SDK Wizard
# Executed Thu Mar 14 13:56:11 EDT 2013 by james
# 
# 
# Tip: The wizard only exposes a small subset of the possible controls
# and layout that can be achieved on a Property Page.  To find out more
# please refer to the Object Model reference documentation for PPGLayout, PPG
# and CustomProperty
# 
# Tip: Don't be concerned about achieving the exact ordering of the parameters
# because they can easily be reordered in the second phase.
# Tip: To add a command to this plug-in, right-click in the 
# script editor and choose Tools > Add Command.
import win32com.client
from win32com.client import constants

null = None
false = 0
true = 1

def XSILoadPlugin( in_reg ):
    in_reg.Author = "James Vecore"
    in_reg.Email  = "james.vecore@gmail.com"
    in_reg.Name   = "KrakatoaRendererPropertyPlugin"
    in_reg.Major  = 1
    in_reg.Minor  = 0

    in_reg.RegisterProperty("Krakatoa Options")
    #RegistrationInsertionPoint - do not remove this line

    return True

def XSIUnloadPlugin( in_reg ):
    strPluginName = in_reg.Name
    Application.LogMessage(str(strPluginName) + str(" has been unloaded."),constants.siVerbose)
    return True

def KrakatoaOptions_Define( in_ctxt ):
    Application.LogMessage("KrakatoaOptions_Define called",constants.siInfo)
    oCustomProperty = in_ctxt.Source
    oCustomProperty.AddParameter3("ErrorOnMissingLicense"     ,constants.siBool  ,True)

    oCustomProperty.AddParameter3("RenderingMethod"           ,constants.siInt4  ,0) # METHOD_PARTICLE = 0, METHOD_VOXEL = 1
    oCustomProperty.AddParameter3("VoxelRadius"               ,constants.siInt4  ,1)
    oCustomProperty.AddParameter3("VoxelSize"                 ,constants.siDouble,0.5)

    # NOTE : defaults to FILTER_BICUBIC
    oCustomProperty.AddParameter3("AttenuationLookupFilter"    ,constants.siInt4  ,1) # FILTER_BILINEAR = 0, FILTER_BICUBIC = 1, FILTER_NEAREST_NEIGHBOR = 2
    oCustomProperty.AddParameter3("AttenuationLookupFilterSize",constants.siInt4  ,1,1,100)

    # NOTE : defaults to FILTER_BILINEAR
    oCustomProperty.AddParameter3("DrawPointFilter"            ,constants.siInt4  ,0) # FILTER_BILINEAR = 0, FILTER_BICUBIC = 1, FILTER_NEAREST_NEIGHBOR = 2
    oCustomProperty.AddParameter3("DrawPointFilterSize"        ,constants.siInt4  ,1,1,100)


    oCustomProperty.AddParameter3("BackgroundR"               ,constants.siDouble,0.0  ,0.0 ,255.0)
    oCustomProperty.AddParameter3("BackgroundG"               ,constants.siDouble,0.0  ,0.0 ,255.0)
    oCustomProperty.AddParameter3("BackgroundB"               ,constants.siDouble,0.0  ,0.0 ,255.0)

    oCustomProperty.AddParameter3("DensityPerParticle"        ,constants.siDouble,5.0)
    oCustomProperty.AddParameter3("DensityExponent"           ,constants.siInt4  ,-1)

    oCustomProperty.AddParameter3("UseEmission"               ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("EmissionStrength"          ,constants.siDouble,5.0)
    oCustomProperty.AddParameter3("EmissionExponent"          ,constants.siInt4  ,-1)

    oCustomProperty.AddParameter3("LightingDensityPerParticle",constants.siDouble,5.0)
    oCustomProperty.AddParameter3("LightingDensityExponent"   ,constants.siInt4  ,-1)

    oCustomProperty.AddParameter3("UseAbsorbtionChannel"      ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("AdditiveMode"              ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("CameraBlur"                ,constants.siBool  ,True)
    # depth of field
    oCustomProperty.AddParameter3("UseDepthOfField"           ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("FStop"                     ,constants.siDouble,1e30)
    oCustomProperty.AddParameter3("FocalLength"               ,constants.siDouble,30.0)
    oCustomProperty.AddParameter3("FocalDistance"             ,constants.siDouble,100.0)
    oCustomProperty.AddParameter3("SampleRate"                ,constants.siDouble,0.1)
    # motion blur
    oCustomProperty.AddParameter3("UseMotionBlur"             ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("ShutterBegin"              ,constants.siDouble,0.0)
    oCustomProperty.AddParameter3("ShutterEnd"                ,constants.siDouble,0.0)
    oCustomProperty.AddParameter3("MBSamples"                 ,constants.siInt4  ,1)
    oCustomProperty.AddParameter3("Jitter"                    ,constants.siBool  ,False)
    # extra channels
    oCustomProperty.AddParameter3("Normals"                   ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("OccludedRGBA"              ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("Velocity"                  ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("ZDepth"                    ,constants.siBool  ,False)

    oCustomProperty.AddParameter3("ExrCompression"            ,constants.siInt4  ,2) # COMPRESSION_NONE, COMPRESSION_RLE, COMPRESSION_ZIPS, COMPRESSION_ZIP,  COMPRESSION_PIZ, COMPRESSION_PXR24, COMPRESSION_B44, COMPRESSION_B44A

    oCustomProperty.AddParameter3("Shader"                      ,constants.siInt4  ,0) # Isotropic=0, Phong=1, Henyey-Greenstein=2,  Schlick=3, Kajiya-Kay Hair=4, Marschner Hair=5

    oCustomProperty.AddParameter3("SpecularLevel"               ,constants.siDouble,100.0,None,None,True,True)
    oCustomProperty.AddParameter3("UseSpecularLevelChannel"     ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("SpecularPower"               ,constants.siDouble,10.0,None,None,True,True)
    oCustomProperty.AddParameter3("UseSpecularPowerChannel"     ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("SpecularShift"               ,constants.siDouble,0.1,-1.0,1.0,True,True)
    oCustomProperty.AddParameter3("UseSpecularShiftChannel"     ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("SpecularGlossiness"          ,constants.siDouble,300.0,None,None,True,True)
    oCustomProperty.AddParameter3("UseSpecularGlossinessChannel",constants.siBool  ,False,None,None,True,True)

    oCustomProperty.AddParameter3("SecondarySpecularLevel"                ,constants.siDouble,90.0,None,None,True,True)
    oCustomProperty.AddParameter3("UseSecondarySpecularLevelChannel"      ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("SecondarySpecularShift"                ,constants.siDouble,-0.1,-1.0,1.0,True,True)
    oCustomProperty.AddParameter3("UseSecondarySpecularShiftChannel"      ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("SecondarySpecularGlossiness"           ,constants.siDouble,30.0,None,None,True,True)
    oCustomProperty.AddParameter3("UseSecondarySpecularGlossinessChannel" ,constants.siBool  ,False,None,None,True,True)

    oCustomProperty.AddParameter3("DiffuseLevel"                    ,constants.siDouble,0.0,0.0,100.0,True,True)
    oCustomProperty.AddParameter3("UseDiffuseLevelChannel"          ,constants.siBool  ,False,None,None,True,True)

    oCustomProperty.AddParameter3("GlintLevel"                      ,constants.siDouble,400.0,None,None,True,True)
    oCustomProperty.AddParameter3("UseGlintLevelChannel"            ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("GlintSize"                       ,constants.siDouble,0.5,0.0,360.0,True,True)
    oCustomProperty.AddParameter3("UseGlintSizeChannel"             ,constants.siBool  ,False,None,None,True,True)
    oCustomProperty.AddParameter3("GlintGlossiness"                 ,constants.siDouble,10.0,0.0,360.0,True,True)
    oCustomProperty.AddParameter3("UseGlintGlossinessChannel"       ,constants.siBool  ,False,None,None,True,True)

    oCustomProperty.AddParameter3("Eccentricity"                    ,constants.siDouble,0.0,-1.0,1.0,True,True)
    oCustomProperty.AddParameter3("UseEccentricityChannel"          ,constants.siBool  ,False,None,None,True,True)

    oCustomProperty.AddParameter3("UseOcclusionMeshes"              ,constants.siBool  ,True)
    oCustomProperty.AddParameter3("OcclusionMeshGroupName"          ,constants.siString,"KrakatoaOcclusion")

    oCustomProperty.AddParameter3("UseLightGroup"                   ,constants.siBool  ,False) # default to all lights in the scene
    oCustomProperty.AddParameter3("LightGroupName"                  ,constants.siString,"KrakatoaLights")

    oCustomProperty.AddParameter3("OutputPrt"                       ,constants.siBool  ,False)
    oCustomProperty.AddParameter3("ComputeLighting"                 ,constants.siBool  ,True)
    oCustomProperty.AddParameter3("PrtPathExpression"               ,constants.siString,"")

    return True

# Tip: Use the "Refresh" option on the Property Page context menu to 
# reload your script changes and re-execute the DefineLayout callback.
def KrakatoaOptions_DefineLayout( in_ctxt ):
    Application.LogMessage("KrakatoaOptions_DefineLayout called",constants.siInfo)
    oLayout = in_ctxt.Source
    oLayout.Clear()
    oLayout.AddTab("Rendering")

    renderingMethods = ["Particle", 0, "Voxel", 1]
    filterOptions    = ["Bilinear", 0, "Bicubic", 1,"Nearest Neighbor",2]
    shaders          = ["Isotropic",0, "Phong"  , 1,"Henyey-Greenstein",2,"Schlick",3,"Kajiya-Kay Hair",4,"Marschner Hair",5]
    compressionTypes = ["None",0, "RLE",1, "ZIPS (Single Scanline)",2, "ZIP (Multi-scanline)",3, "PIZ", 4, "PXR24", 5, "B44", 6, "B44A", 7]
    dataTypes        = ["Unsigned Integer (32-bit)",0, "Half Float (16-bit)", 1, "Float (32-bit)", 2]

    oLayout.AddEnumControl("RenderingMethod"    ,renderingMethods, "Rendering Method")

    oLayout.AddGroup("Voxel Rendering Mode Options",True)
    oLayout.AddItem("VoxelRadius", "Voxel Radius")
    oLayout.AddItem("VoxelSize"  , "Voxel Size")
    oLayout.EndGroup()

    oLayout.AddGroup("Particle Rendering Mode Options",True)
    oLayout.AddEnumControl("DrawPointFilter" , filterOptions, "Draw Point Filter")
    oLayout.AddItem("DrawPointFilterSize"    , "Draw Point Filter Size") # only show if FILTER_BILINEAR (0)
    oLayout.AddEnumControl("AttenuationLookupFilter", filterOptions, "Attenuation Lookup Filter")
    oLayout.AddItem("AttenuationLookupFilterSize", "Attenuation Lookup Filter Size") # only show if FILTER_BILINEAR (0)
    oLayout.EndGroup()

    oLayout.AddItem("ErrorOnMissingLicense"     ,"Error On Missing License")
    oLayout.AddColor("BackgroundR"              ,"Background Color" )
    oLayout.AddItem("DensityPerParticle"        ,"Density Per Particle")
    oLayout.AddItem("DensityExponent"           ,"Density Exponent")
    oLayout.AddItem("UseEmission"               ,"Use Emission")
    oLayout.AddItem("EmissionStrength"          ,"Emission Strength")
    oLayout.AddItem("EmissionExponent"          ,"Emission Exponent")
    oLayout.AddItem("LightingDensityPerParticle","Lighting Density Per Particle")
    oLayout.AddItem("LightingDensityExponent"   ,"Lighting Density Exponent")
    oLayout.AddItem("UseAbsorbtionChannel"      ,"Use Absorbtion Channel")
    oLayout.AddItem("AdditiveMode"              ,"Additive Mode")
    oLayout.AddItem("CameraBlur"                ,"Enable Camera Blur")


    # depth of field
    oLayout.AddTab("Depth of Field")
    oLayout.AddItem("UseDepthOfField"           ,"Use Depth of Field")
    # TODO: offset option to pull these from the camera directly
    oLayout.AddItem("FStop"                     ,"F-Stop")
    oLayout.AddItem("FocalLength"               ,"Focal Length")
    oLayout.AddItem("FocalDistance"             ,"Focal Distance")
    oLayout.AddItem("SampleRate"                ,"Sample Rate")

    # motion blur
    oLayout.AddTab("Motion Blur")
    oLayout.AddItem("UseMotionBlur"             ,"Use Motion Blur")
    oLayout.AddItem("ShutterBegin"              ,"Shutter Begin")
    oLayout.AddItem("ShutterEnd"                ,"Shutter End")
    oLayout.AddItem("MBSamples"                 ,"Samples")
    oLayout.AddItem("Jitter"                    ,"Jitter")

    oLayout.AddTab("Output Channels")
    oLayout.AddItem("Normals"                   ,"Normals")
    oLayout.AddItem("OccludedRGBA"              ,"Occluded RGBA")
    oLayout.AddItem("Velocity"                  ,"Velocity")
    oLayout.AddItem("ZDepth"                    ,"ZDepth")

    oLayout.AddEnumControl("ExrCompression" , compressionTypes, "Exr Compression Type")

    oLayout.AddTab("Scene")
    oLayout.AddItem("UseLightGroup"             ,"Use Light Group")
    oLayout.AddItem("LightGroupName"            ,"Light Group Name")
    oLayout.AddItem("UseOcclusionMeshes"        ,"Use Occlusion Meshes")
    oLayout.AddItem("OcclusionMeshGroupName"    ,"Occlusion Mesh Group Name")

    oLayout.AddTab("Shader Options")
    oLayout.AddEnumControl("Shader", shaders)
    oLayout.AddItem("DiffuseLevel","Diffuse Level")
    oLayout.AddItem("UseDiffuseLevelChannel","Use Diffuse Level Channel")
    oLayout.AddItem("SpecularLevel","Specular Level")
    oLayout.AddItem("UseSpecularLevelChannel","Use Specular Level Channel")
    oLayout.AddItem("SpecularPower","Specular Power")
    oLayout.AddItem("UseSpecularPowerChannel","Use Specular Power Channel")
    oLayout.AddItem("SpecularShift","Specular Shift")
    oLayout.AddItem("UseSpecularShiftChannel","Use Specular Shift Channel")
    oLayout.AddItem("SpecularGlossiness","Specular Glossiness")
    oLayout.AddItem("UseSpecularGlossinessChannel","Use Specular Glossiness Channel")
    oLayout.AddItem("SecondarySpecularLevel","Secondary Specular Level")
    oLayout.AddItem("UseSecondarySpecularLevelChannel","Use Secondary Specular Level Channel")
    oLayout.AddItem("SecondarySpecularShift","Secondary Specular Shift")
    oLayout.AddItem("UseSecondarySpecularShiftChannel","Use Secondary Specular Shift Channel")
    oLayout.AddItem("SecondarySpecularGlossiness","Secondary Specular Glossiness")
    oLayout.AddItem("UseSecondarySpecularGlossinessChannel","Use Secondary Specular Glossiness Channel")
    oLayout.AddItem("GlintLevel","Glint Level")
    oLayout.AddItem("UseGlintLevelChannel","Use Glint Level Channel")
    oLayout.AddItem("GlintSize","Glint Size")
    oLayout.AddItem("UseGlintSizeChannel","Use Glint Size Channel")
    oLayout.AddItem("GlintGlossiness","Glint Glossiness")
    oLayout.AddItem("UseGlintGlossinessChannel","Use Glint Glossiness Channel")
    oLayout.AddItem("Eccentricity","Eccentricity")
    oLayout.AddItem("UseEccentricityChannel","Use Eccentricity Channel")

    oLayout.AddTab("Output Prt")
    oLayout.AddItem("OutputPrt", "Output .prt file instead of image")
    oLayout.AddItem("ComputeLighting", "Computing Lighting Channel")
    oItem = oLayout.AddItem("PrtPathExpression", "Path", "FilePath")
    oItem.SetAttribute("FileFilter", "Prt files (*.prt)|*.prt")
    oItem.SetAttribute("OpenFile", False)
    oItem.SetAttribute("MustExist", False)


    return True

def Krakatoa_Options_OnInit( ):
    Application.LogMessage("KrakatoaOptions_OnInit called",constants.siInfo)

def Krakatoa_Options_OnClosed( ):
    Application.LogMessage("KrakatoaOptions_OnClosed called",constants.siInfo)


def Krakatoa_Options_RenderingMethod_OnChanged( ):
    oCusProp = PPG.Inspected(0)

    if oCusProp.RenderingMethod.Value == 0:
        oCusProp.VoxelRadius.ReadOnly = True
        oCusProp.VoxelSize.ReadOnly = True
        oCusProp.AttenuationLookupFilter.ReadOnly = False
        oCusProp.AttenuationLookupFilterSize.ReadOnly = False
        oCusProp.DrawPointFilter.ReadOnly = False
        oCusProp.DrawPointFilterSize.ReadOnly = False
    else:
        oCusProp.VoxelRadius.ReadOnly = False
        oCusProp.VoxelSize.ReadOnly = False
        oCusProp.AttenuationLookupFilter.ReadOnly = True
        oCusProp.AttenuationLookupFilterSize.ReadOnly = True
        oCusProp.DrawPointFilter.ReadOnly = True
        oCusProp.DrawPointFilterSize.ReadOnly = True

    PPG.Refresh()

def Krakatoa_Options_Shader_OnChanged( ):
    oCusProp = PPG.Inspected(0)

    defaultValue = True
    if oCusProp.Shader.Value == 5:
        defaultValue = False

    oCusProp.DiffuseLevel.ReadOnly = defaultValue
    oCusProp.UseDiffuseLevelChannel.ReadOnly = defaultValue
    oCusProp.SpecularLevel.ReadOnly = defaultValue
    oCusProp.UseSpecularLevelChannel.ReadOnly = defaultValue
    oCusProp.SpecularPower.ReadOnly = defaultValue
    oCusProp.UseSpecularPowerChannel.ReadOnly = defaultValue
    oCusProp.SpecularShift.ReadOnly = defaultValue
    oCusProp.UseSpecularShiftChannel.ReadOnly = defaultValue
    oCusProp.SpecularGlossiness.ReadOnly = defaultValue
    oCusProp.UseSpecularGlossinessChannel.ReadOnly = defaultValue

    oCusProp.SecondarySpecularLevel.ReadOnly = defaultValue
    oCusProp.UseSecondarySpecularLevelChannel.ReadOnly = defaultValue
    oCusProp.SecondarySpecularShift.ReadOnly = defaultValue
    oCusProp.UseSecondarySpecularShiftChannel.ReadOnly = defaultValue
    oCusProp.SecondarySpecularGlossiness.ReadOnly = defaultValue
    oCusProp.UseSecondarySpecularGlossinessChannel.ReadOnly = defaultValue

    oCusProp.GlintLevel.ReadOnly = defaultValue
    oCusProp.UseGlintLevelChannel.ReadOnly = defaultValue
    oCusProp.GlintSize.ReadOnly = defaultValue
    oCusProp.UseGlintSizeChannel.ReadOnly = defaultValue
    oCusProp.GlintGlossiness.ReadOnly = defaultValue
    oCusProp.UseGlintGlossinessChannel.ReadOnly = defaultValue

    oCusProp.Eccentricity.ReadOnly = defaultValue
    oCusProp.UseEccentricityChannel.ReadOnly = defaultValue

    if oCusProp.Shader.Value == 0: # isotropic
        # no params do nothing and leave them all disabled
        pass
    elif oCusProp.Shader.Value == 1: # phong
        oCusProp.SpecularLevel.ReadOnly = False
        oCusProp.UseSpecularLevelChannel.ReadOnly = False
        oCusProp.SpecularPower.ReadOnly = False
        oCusProp.UseSpecularPowerChannel.ReadOnly = False
    elif oCusProp.Shader.Value == 2: # henyey_greenstein
        oCusProp.Eccentricity.ReadOnly = False
        oCusProp.UseEccentricityChannel.ReadOnly = False
    elif oCusProp.Shader.Value == 3: # schlick
        oCusProp.Eccentricity.ReadOnly = False
        oCusProp.UseEccentricityChannel.ReadOnly = False
    elif oCusProp.Shader.Value == 4: # kajiya_kay
        oCusProp.SpecularLevel.ReadOnly = False
        oCusProp.UseSpecularLevelChannel.ReadOnly = False
        oCusProp.SpecularPower.ReadOnly = False
        oCusProp.UseSpecularPowerChannel.ReadOnly = False
    elif oCusProp.Shader.Value == 5: # marschner
        # we set a different default here to leave all params on so turn off what we don't want
        oCusProp.SpecularPower.ReadOnly = True
        oCusProp.UseSpecularPowerChannel.ReadOnly = True
        oCusProp.Eccentricity.ReadOnly = True
        oCusProp.UseEccentricityChannel.ReadOnly = True

    PPG.Refresh()

